services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: skyoffice-server-prod
    restart: unless-stopped
    expose:
      - "2567"
    networks:
      - default
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=${SERVER_VIRTUAL_HOST}
      - VIRTUAL_PORT=2567
      - LETSENCRYPT_HOST=${SERVER_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: skyoffice-client-prod
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - default
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}


networks:
  default:
    external:
      name: nginx-proxy_default
