services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: skyoffice-server-prod
    restart: unless-stopped
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: skyoffice-client-prod
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}


networks:
  default:
    external:
      name: nginx-proxy_default
