services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: skyoffice-server-prod
    restart: unless-stopped
    ports:
      - "2567:2567"
    networks:
      - default
    environment:
      - NODE_ENV=production

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: skyoffice-client-prod
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - /usr/share/nginx/html
    networks:
      - default
    environment:
      - VIRTUAL_HOST=skyoffice.breezegroup.jp


networks:
  default:
    external:
      name: nginx-proxy_default
